### ISSUE TITLE
Add an option to change the cookie monster by an eggplant

### ISSUE THREAD

**Issue by SamuelLorrain** [AzenoX/cookies-duplication-alert-extension#1]
I like eggplant, and I think it would be better if we had an option to chnage the cookie gif by an eggplant. Eggplant are cool

**Comment by AlexisHyt** [comment]
I need to add an options panel (I plan to add sites whitelist as well), maybe in the next version :P

**Comment by AlexisHyt** [comment]
Your wishes have been implemented in the version 1.1.0 👍
